version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 


  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env

    environment:
      MONGODB_URI: mongodb+srv://virujopale99:Viru%40123.45@blog-web.nr5x3jq.mongodb.net/Todo
